# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build and Test .NET projects

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

    paths-ignore:
      - "**/*.md"
      - "**/*.gitignore"
      - "**/*.gitattributes"

  workflow_dispatch:
    inputs:
      reason:
        description: "The reason for running the workflow"
        required: true
        default: "Manual run"

jobs:
  build:
    if: github.event_name == 'workflow_dispatch' || github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')

    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_NOLOGO: true
      DOTNET_GENERATE_ASPNET_CERTIFICATE: false
      DOTNET_ADD_GLOBAL_TOOLS_TO_PATH: false
      DOTNET_MULTILEVEL_LOOKUP: 0
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      BUILD_CONFIG: 'Release'
      SOLUTION: 'BlazorApp.sln'
      TEST-RESULTS: '*/Test Results/**/*.trx'

    permissions:
      checks: write
      pull-requests: write

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: ./Global.json

      - name: Workload install
        run: dotnet workload restore
    
      - name: Restore dependencies
        run: dotnet restore $SOLUTION

      - name: Build
        run: dotnet build $SOLUTION --configuration $BUILD_CONFIG --no-restore

      - name: Unit Test
        run: dotnet test --configuration $BUILD_CONFIG --no-restore --no-build --logger trx --results-directory TestResults

      - name: Upload Event File
        uses: actions/upload-artifact@v4
        with:
          name: Event File
          path: ${{ github.event_path }}

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Test Results
          path: TestResults

      - name: Codecov
        uses: codecov/codecov-action@v5.1.1

      - name: Upload dotnet test results
        uses: actions/upload-artifact@v4
        with:
          name: BlazorApp-test-results
          path: TestResults

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3.0.3
        with:
          versionSpec: "5.x"

      - name: Use GitVersion
        id: gitversion # step id used as reference for output values
        uses: gittools/actions/gitversion/execute@v3.0.3
      - run: |
          echo "FullSemVer: ${{ steps.gitversion.outputs.fullSemVer }}"

        # Use always() to always run this step to
        # publish test results when there are test failures
        if: ${{ always() }}
